### ISSUE TITLE
pgroll not getting installed

### ISSUE THREAD

**Issue by althaf004** [xataio/pgroll#173]
hi Team, i tried to install pgroll and im getting below error

![image](https://github.com/xataio/pgroll/assets/83403907/b2f4041c-7921-4da4-a730-a15033310274)

**Comment by exekias** [comment]
Hi @althaf004, thank you for reporting this!

I just tried these steps and they worked for me, could you please check if your go binaries folder is in our `PATH` environment variable?

For me:
```
$ go env GOPATH
/Users/exekias/go

$ export PATH=$PATH:/Users/exekias/go/bin

$ pgroll -v
pgroll version development
```

**Comment by tsg** [comment]
Worth noting that we also publish already built binaries: https://github.com/xataio/pgroll/releases

So, alternatively, I think you should be able to download and run:

```
curl -L -o pgroll https://github.com/xataio/pgroll/releases/download/v0.2.0/pgroll.linux.amd64
./pgroll -v
```

**Comment by althaf004** [comment]
@tsg below is what i got by executing above command:

![image](https://github.com/xataio/pgroll/assets/83403907/6e19aced-1b77-43cd-990c-6ad3838fb0ee)

Is it correct?

**Comment by tsg** [comment]
Unfortunately you are getting CGO errors. We will disable CGO in the binaries, but until then, can you try as suggested by @exekias. Sorry for the noise.

**Comment by althaf004** [comment]
> Hi @althaf004, thank you for reporting this!
> 
> I just tried these steps and they worked for me, could you please check if your go binaries folder is in our `PATH` environment variable?
> 
> For me:
> 
> ```
> $ go env GOPATH
> /Users/exekias/go
> 
> $ export PATH=$PATH:/Users/exekias/go/bin
> 
> $ pgroll -v
> pgroll version development
> ```

![image](https://github.com/xataio/pgroll/assets/83403907/191b0893-8f28-40c1-80b9-43adb7e3837c)


what should be given in $path, because im new to these codings. Thanks

**Comment by exekias** [comment]
We have just released a new version that aims at fixing the CGO problem you faced, this new version should work for you:

https://github.com/xataio/pgroll/releases/download/v0.2.1/pgroll.linux.amd64

Do you mind retrying the steps from https://github.com/xataio/pgroll/issues/173#issuecomment-1750503020?

**Comment by althaf004** [comment]
Thanks Got this installation working.
