### ISSUE TITLE
Create a Homebrew recipe to install pgroll

### ISSUE THREAD

**Issue by exekias** [xataio/pgroll#175]
We can leverage [Homebrew](https://brew.sh/) in order to make `pgroll` easier to install. Right now the only options are manually downloading the binary or installing from source.

**Comment by exekias** [comment]
One option could be to integrate https://goreleaser.com/ and do releases with it. It could cover Homebrew, but also cross compiling or docker images

**Comment by sFritsch09** [comment]
I would like to work on this #hacktoberfest 🚀

**Comment by exekias** [comment]
awesome! go for it!

**Comment by sFritsch09** [comment]
PR: https://github.com/xataio/pgroll/pull/180
