### ISSUE TITLE
Purpose of drop_column down is unclear in the documentation

### ISSUE THREAD

**Issue by simonw** [xataio/pgroll#257]
This section here:

https://github.com/xataio/pgroll/blob/9d2515963865ba4b5b71fe0ff9ea85e8ce9e2ddf/docs/README.md#drop-column

> A drop column operation drops a column from an existing table.
>
> **drop column** operations have this structure:
>
> ```json
> {
>    "drop_column": {
>     "table": "name of table",
>     "column": "name of column to drop",
>     "down": "SQL expression"
>   }
> }

It's not obvious to me what the `"down"` key here is used for.

**Comment by exekias** [comment]
Thank you for opening this issue!

Down migrations are applied to adapt data from the latest schema version into the previous one. During the active migration period, you will have a new schema version that doesn't have the column, while the old schema (that has it) is still available.

If the deployed version of your application expects a value in that column (or there is a constraint requiring it, ie NOT NULL), `down` function can be used to ensure that all inserts/updates happening in the new version of the schema get a valid value backfilled into this column for the old version of the schema (and its clients) to consume.

I realize docs may need clarification on this, we can use this issue to ensure we update them!
