### ISSUE TITLE
boot postresql system easily for testing

### ISSUE THREAD

**Issue by gedw99** [xataio/pgroll#268]
I know docker is the "one true way" but this makes testing very quick.

It is a golang package that pulls and boots postresql for Windows, Darwin, Linux.

https://github.com/fergusstrange/embedded-postgres

Its a very simple boot process, like in this example: https://github.com/nakulbh/dbping/blob/main/dbping.go

**Comment by andrew-farries** [comment]
Thanks for opening the issue @gedw99 

https://github.com/fergusstrange/embedded-postgres looks interesting but I don't see enough of a benefit vs our existing [testcontainers-go](https://github.com/testcontainers/testcontainers-go) based setup to consider making the switch currently.
