### ISSUE TITLE
Questions about setup with zero downtime usage

### ISSUE THREAD

**Issue by dolezvo1** [xataio/pgroll#371]
Hi, I'm sorry, this is not an issue with the program as such, but I'm just not completely clear on the recommended usage and the implications from reading the documentation. What I'm not clear about is mainly this: in the readme you say to set the search path for new clients like this:
```pgsql
SET search_path TO 'public_initial_migration';
```
Does that mean that the new clients will be able to use this search path without issues any issues after the migration is complete, i.e. that the temporary schema is not deleted? If so, are there any safeguards in case of a rollback? My first thought was actually to do something like the following, but I think that is not actually safe in case of a rollback, so I wanted to check if there is a better way to do this:
```pgsql
SET search_path TO public_initial_migration, public;
```

**Comment by dolezvo1** [comment]
Oh, I see, it seems that the new schema is not being deleted, so that seems promising? I assume that means that in case of a rollback, new clients simply have a `search_path` with one non-existent schema, and therefore can't cause any harm?

**Comment by exekias** [comment]
pgroll ensures that there is at least one schema version active at all times. We only delete the old version schema after you complete a new migration. Ideally the workflow would be as this:

* Current app using the current version of the schema (set in the search_path).
* Start a new migration, now old & new version schemas are available
* Deploy the new version of the app, using the new version of the schema
* If the deployment process goes well, tear down the old version fo the app. Old version schema is no longer being used
* Complete the migration, this will remove the old version of the schema, and keep the new one.

**Comment by dolezvo1** [comment]
Thanks!
