### ISSUE TITLE
Allow creating different types of indexes and/or return more information about an index type

### ISSUE THREAD

**Issue by eemmiillyy** [xataio/pgroll#378]
This is a feature request:

- It would be useful to allow creating indexes other than btree via pgroll.
- It would also be useful to have information created about index types created (also via SQL) on the schema so that we can reconstruct the create index statement for the user that was run.

**Comment by kvch** [comment]
What do you want to do with the reconstructed command? I can return the complete index definition statement. However, with pgroll we create the index concurrently (to avoid locking tables) and the reconstructed statement does not contain it by default.

**Comment by eemmiillyy** [comment]
I want to be able to list the indexes.  I also want to be able to show example SQL for creating indexes. 

Probably returning just the index definition is enough and we don't need to reconstruct any statements.

Does that make sense? @kvch

**Comment by kvch** [comment]
The index definition we can get from PostgreSQL is a complete statement for creating the index e.g. `CREATE INDEX idx_users_name_hash ON public.users USING hash (name) WITH (fillfactor='70')`. But it seems you also need index type and other info for pretty displays.
