### ISSUE TITLE
Unique migration numbering required?

### ISSUE THREAD

**Issue by mikl** [xataio/pgroll#382]
In your examples, you name your migrations something like `01_do_this`, `02_do_that`, `03_do_something`.

A problem we often have is when one developer creates `0134_add_table_foo` in his branch and another developer creates `0134_add_table_bar`, so once both are merged we have two migrations with the same number.

Would this be problem with `pgroll`, would the duplicate number cause one migration not to be run or other problems, or is it just used to have the files in a consistent order?

**Comment by exekias** [comment]
Hi @mikl!

pgroll is not really opinionated about migration names, we use this in the examples so users can follow them in order. This means that pgroll doesn't use the numbers in the migration files at all, the only rule is that migration names cannot repeat.

If for any reason you land on that scenario after merging 2 PRs, things should work as long as the migrations are not incompatible between them, something that pgroll would detect.

hope this answers your question?

**Comment by mikl** [comment]
@exekias thanks for the clarification, that sounds good.
