### ISSUE TITLE
Support for drop default on a column

### ISSUE THREAD

**Issue by divyenduz** [xataio/pgroll#450]
The following operation is not supported natively by pgroll. 

```sql
ALTER TABLE public."Pet" ALTER COLUMN id DROP DEFAULT;
```

Current workaround is to use SQL the [escape hatch](https://github.com/xataio/pgroll/blob/main/examples/05_sql.json).

**Comment by andrew-farries** [comment]
Yes, this belongs on `OpAlterColumn`.

I think we could handle this by distinguishing the case where `default` is explicitly set to `null` vs omitted from the operation in the same way as we did in https://github.com/xataio/pgroll/pull/345 for removing comments from tables and columns.

**Comment by andrew-farries** [comment]
The following statements look to have slightly different effects:

```sql
alter table products alter column name set default NULL
```

results in a column that looks like this:

```
 name   | character varying(255) |           |          | NULL::character varying                          | extended |             |              |
```

whereas:

```sql
alter table products alter column name drop default
```

produces a column like this:

```
 name   | character varying(255) |           |          |                                                  | extended |             |              |
```

i.e Postgres catalogs record a default of `NULL` vs no default slightly differently. If we wanted to implement this we'd need to distinguish:

```json
  "operations": [
    {
      "alter_column": {
        "table": "products",
        "column": "name",
        "default": "NULL"
      }
    }
  ]
```

from:

```json
  "operations": [
    {
      "alter_column": {
        "table": "products",
        "column": "name",
        "default": null
      }
    }
  ]
```

WDYT?

**Comment by ryanslade** [comment]
Ok, so we would implement the second case where the value is `null` by dropping the default. I'm still not totally clear on the semantic difference between no default and a default of `NULL`.

**Comment by andrew-farries** [comment]
I don't think there is a difference in practical terms - looks as though Postgres just records each case differently in the system catalogs:

Using this query to retrieve information about column defaults:

```sql
SELECT
     a.attname AS column_name,
     pg_get_expr(ad.adbin, ad.adrelid) AS default_value
 FROM
     pg_catalog.pg_attrdef ad
     JOIN pg_catalog.pg_attribute a ON ad.adnum = a.attnum
 WHERE
     a.attrelid = 'products'::regclass;
```

a `DEFAULT` set to `NULL` still shows up in the result set:

```
+-------------+--------------------------------------------------+
| column_name | default_value                                    |
|-------------+--------------------------------------------------|
| name        | NULL::character varying                          |
+-------------+--------------------------------------------------+
```

whereas a dropped `DEFAULT` is no longer present in the catalogs as having a default (`pg_attribute.atthasdef` is false for that column).

This is on Postgres 17; not sure if the behaviour is consistent between versions.

It looks as though dropping a `DEFAULT` is 'cleaner' than setting it to `NULL` if nothing else.
