### ISSUE TITLE
Add guards for names max length

### ISSUE THREAD

**Issue by exekias** [xataio/pgroll#64]
names in postgres have a max length of 63 chars by default. We generate names in many places, like:

- Version schema names
- Temporary table/column names
- indices
- triggers
- etc

We should make sure we don't generate names longer than the expected max, as that could cause issues down the line.

https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

**Comment by pucke-uninow** [comment]
I would like to work on this one.
